apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "ingest-src-mongodb-cdc-tables-avro-e173470a"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: edh
spec:
  class: io.debezium.connector.mongodb.MongoDbConnector
  tasksMax: 2
  config:
    key.converter: "io.confluent.connect.avro.AvroConverter"
    key.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schema-registry-cp-schema-registry:8081"
    mongodb.hosts: "rs0/20.75.33.14:27017"
    mongodb.password: "${file:/opt/kafka/external-configuration/connector-config-mongodb/mongodb-credentials.properties:mongodb_password}"
    mongodb.user: "${file:/opt/kafka/external-configuration/connector-config-mongodb/mongodb-credentials.properties:mongodb_username}"
    mongodb.name: "cdc-mongodb"
    database.whitelist: "owshq"
    collection.whitelist: "owshq.user, owshq.payments"
    connect.backoff.initial.delay.ms: 2000
    connect.backoff.max.delay.ms: 160000
    mongodb.members.auto.discover: False
    snapshot.max.threads: 2
    initial.sync.max.threads: 2
    poll.interval.ms: 2000
    sanitize.field.names: True
